import type { User, Task, Department, TaskTemplate } from "./types"

export const mockDepartments: Department[] = [
  {
    id: "dept1",
    name: "BOH",
  },
  {
    id: "dept2",
    name: "FOH",
  },
  {
    id: "dept3",
    name: "Quản lý",
  },
  {
    id: "dept4",
    name: "Hành chính",
  },
]

export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Nam",
    role: "Đầu bếp phụ",
    dept: "BOH",
  },
  {
    id: "user2",
    name: "Linh",
    role: "Quản lý chi nhánh",
    dept: "Quản lý",
  },
  {
    id: "user3",
    name: "Tuấn",
    role: "Đầu bếp trưởng",
    dept: "BOH",
  },
  {
    id: "user4",
    name: "Mai",
    role: "Thu ngân",
    dept: "FOH",
  },
  {
    id: "user5",
    name: "Huy",
    role: "Phục vụ",
    dept: "FOH",
  },
  {
    id: "user6",
    name: "Lan",
    role: "Kế toán",
    dept: "Hành chính",
  },
  {
    id: "user7",
    name: "Minh",
    role: "Quản lý phụ",
    dept: "Quản lý",
  },
  {
    id: "user8",
    name: "Thanh",
    role: "Lễ tân",
    dept: "FOH",
  },
]

export const mockTaskTemplates: TaskTemplate[] = [
  {
    id: "template1",
    name: "Kiểm kê hàng tồn kho",
    title: "Kiểm kê hàng tồn kho cuối ngày",
    description: "Kiểm tra và cập nhật số lượng hàng tồn kho sau khi đóng cửa",
    dept: "BOH",
    priority: "Medium",
    checklistItems: [
      "Kiểm tra số lượng thịt",
      "Kiểm tra số lượng rau củ",
      "Kiểm tra số lượng gia vị",
      "Cập nhật sổ kho",
    ],
  },
  {
    id: "template2",
    name: "Chuẩn bị mở cửa",
    title: "Chuẩn bị nhà hàng trước khi mở cửa",
    description: "Thực hiện các công việc chuẩn bị trước khi nhà hàng mở cửa",
    dept: "FOH",
    priority: "High",
    checklistItems: ["Lau dọn bàn ghế", "Chuẩn bị khăn ăn và đồ dùng", "Kiểm tra menu", "Kiểm tra hệ thống POS"],
  },
  {
    id: "template3",
    name: "Chuẩn bị món đặc biệt",
    title: "Chuẩn bị món đặc biệt cuối tuần",
    description: "Lên kế hoạch và chuẩn bị nguyên liệu cho món đặc biệt cuối tuần",
    dept: "BOH",
    priority: "Medium",
    isSequential: true,
    defaultAssignees: [
      {
        role: "Đầu bếp trưởng",
        timeAllocation: 2,
      },
      {
        role: "Đầu bếp phụ",
        timeAllocation: 3,
      },
      {
        role: "Quản lý chi nhánh",
        timeAllocation: 1,
      },
    ],
  },
  {
    id: "template4",
    name: "Báo cáo doanh thu",
    title: "Lập báo cáo doanh thu hàng ngày",
    description: "Tổng hợp và phân tích doanh thu trong ngày",
    dept: "Hành chính",
    priority: "High",
    isSequential: true,
    defaultAssignees: [
      {
        role: "Thu ngân",
        timeAllocation: 1,
      },
      {
        role: "Kế toán",
        timeAllocation: 2,
      },
      {
        role: "Quản lý chi nhánh",
        timeAllocation: 1,
      },
    ],
  },
  {
    id: "template5",
    name: "Đào tạo nhân viên mới",
    title: "Đào tạo nhân viên mới",
    description: "Hướng dẫn quy trình làm việc cho nhân viên mới",
    dept: "Quản lý",
    priority: "Medium",
    checklistItems: [
      "Giới thiệu về nhà hàng",
      "Hướng dẫn quy trình phục vụ",
      "Đào tạo sử dụng hệ thống",
      "Đánh giá sau đào tạo",
    ],
  },
]

export const mockTasks: Task[] = [
  {
    id: "task1",
    title: "Bổ sung thịt bò USDA",
    description: "Kiểm tra kho và bổ sung thịt bò USDA cho quầy buffet",
    responsible: "user1",
    accountable: "user2",
    consulted: "user3",
    informed: "",
    dept: "BOH",
    priority: "High",
    status: "Done",
    due: "2025-03-24T14:00:00.000Z",
    created: "2025-03-24T08:00:00.000Z",
  },
  {
    id: "task2",
    title: "Vệ sinh bếp nướng",
    description: "Vệ sinh kỹ tất cả các bếp nướng sau khi đóng cửa",
    responsible: "user3",
    accountable: "user2",
    consulted: "",
    informed: "",
    dept: "BOH",
    priority: "Medium",
    status: "To Do",
    due: "2025-03-25T22:00:00.000Z",
    created: "2025-03-24T09:30:00.000Z",
  },
  {
    id: "task3",
    title: "Xử lý thanh toán cuối ngày",
    description: "Đối chiếu tất cả các khoản thanh toán và chuẩn bị tiền gửi",
    responsible: "user4",
    accountable: "user2",
    consulted: "user6",
    informed: "",
    dept: "FOH",
    priority: "High",
    status: "In Progress",
    due: "2025-03-24T22:30:00.000Z",
    created: "2025-03-24T10:15:00.000Z",
  },
  {
    id: "task4",
    title: "Chuẩn bị báo cáo tài chính tháng",
    description: "Tổng hợp dữ liệu bán hàng và chi phí cho tháng 3",
    responsible: "user6",
    accountable: "user2",
    consulted: "",
    informed: "user7",
    dept: "Hành chính",
    priority: "Medium",
    status: "In Progress",
    due: "2025-03-31T17:00:00.000Z",
    created: "2025-03-20T11:00:00.000Z",
  },
  {
    id: "task5",
    title: "Đào tạo nhân viên phục vụ mới",
    description: "Hướng dẫn 3 nhân viên mới về thực đơn và tiêu chuẩn phục vụ",
    responsible: "user5",
    accountable: "user7",
    consulted: "",
    informed: "user2",
    dept: "FOH",
    priority: "Medium",
    status: "Done",
    due: "2025-03-23T15:00:00.000Z",
    created: "2025-03-21T13:45:00.000Z",
  },
  {
    id: "task6",
    title: "Đặt đĩa và dụng cụ ăn mới",
    description: "Thay thế các món bị hỏng và bổ sung cho cuối tuần đông khách",
    responsible: "user7",
    accountable: "user2",
    consulted: "user6",
    informed: "",
    dept: "Quản lý",
    priority: "Low",
    status: "Done",
    due: "2025-03-22T12:00:00.000Z",
    created: "2025-03-20T14:30:00.000Z",
  },
  {
    id: "task7",
    title: "Cập nhật thực đơn đặc biệt cuối tuần",
    description: "Tạo các món khuyến mãi mới cho cuối tuần",
    responsible: "user3",
    accountable: "user2",
    consulted: "",
    informed: "user8",
    dept: "BOH",
    priority: "High",
    status: "Overdue",
    due: "2025-03-23T10:00:00.000Z",
    created: "2025-03-21T09:00:00.000Z",
  },
  {
    id: "task8",
    title: "Sắp xếp lịch nhân viên tuần tới",
    description: "Chuẩn bị và công bố lịch làm việc cho tuần tới",
    responsible: "user7",
    accountable: "user2",
    consulted: "",
    informed: "",
    dept: "Quản lý",
    priority: "High",
    status: "To Do",
    due: "2025-03-26T17:00:00.000Z",
    created: "2025-03-24T11:20:00.000Z",
  },
  {
    id: "task9",
    title: "Kiểm tra và bảo trì tủ lạnh",
    description: "Đảm bảo tất cả tủ lạnh đều ở nhiệt độ thích hợp và sạch sẽ",
    responsible: "user1",
    accountable: "user3",
    consulted: "",
    informed: "",
    dept: "BOH",
    priority: "Medium",
    status: "In Progress",
    due: "2025-03-25T11:00:00.000Z",
    created: "2025-03-24T08:45:00.000Z",
  },
  {
    id: "task10",
    title: "Chuẩn bị đón khách đoàn lớn",
    description: "Nhóm VIP 20 người đến lúc 7 giờ tối, chuẩn bị đón tiếp đặc biệt",
    responsible: "user8",
    accountable: "user7",
    consulted: "user5",
    informed: "user2",
    dept: "FOH",
    priority: "High",
    status: "To Do",
    due: "2025-03-24T18:00:00.000Z",
    created: "2025-03-23T16:30:00.000Z",
  },
  // Example of a sequential task
  {
    id: "task11",
    title: "Chuẩn bị món đặc biệt cuối tuần",
    description: "Lên kế hoạch và chuẩn bị nguyên liệu cho món đặc biệt cuối tuần",
    responsible: "user3", // Main responsible person
    accountable: "user2",
    consulted: "",
    informed: "",
    dept: "BOH",
    priority: "High",
    status: "In Progress",
    due: "2025-03-26T17:00:00.000Z",
    created: "2025-03-24T11:20:00.000Z",
    isSequential: true,
    assignees: [
      {
        userId: "user3", // Đầu bếp trưởng
        timeAllocation: 2,
        isCompleted: true,
        startTime: "2025-03-24T11:20:00.000Z",
        endTime: "2025-03-24T13:20:00.000Z",
      },
      {
        userId: "user1", // Đầu bếp phụ
        timeAllocation: 3,
        isCompleted: false,
        startTime: "2025-03-24T13:20:00.000Z",
      },
      {
        userId: "user2", // Quản lý chi nhánh
        timeAllocation: 1,
        isCompleted: false,
      },
    ],
    checklistItems: ["Lên danh sách nguyên liệu", "Chuẩn bị sơ chế", "Thử nghiệm công thức", "Hoàn thiện món ăn"],
  },
]

